setwd("/datos/")
load("comprobar.RData")


# Analysis 1. R vs NR (R vs NR)


### Step 1. Libraries ###

library(GEOquery)
library(DESeq2)
library(tidyverse)
library(pheatmap)
library(clusterProfiler)
library(org.Hs.eg.db)
library(openxlsx)
library(fgsea)
library(xml2)
library(tibble)
library(stringr)
library(EnhancedVolcano)
library(ggplot2)
library(AnnotationDbi)
library(dplyr)
library(conflicted)
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("intersect", "base")

### Step 2. Load count matrix and annotate R / NR groups ###

# Load raw counts
counts <- read.delim(gzfile("bulk_rna_seq_raw_counts.txt.gz"), 
                     row.names = 1, 
                     check.names = FALSE)

# Remove geneName column (we will use rownames)
counts <- counts[, -1]  # removes geneName column

# Check structure
dim(counts)
head(counts)[, 1:5]

# Create group vector (R/NR)
# Define samples
r <- c("P3", "P5", "P27", "P31", "P32", "P36", 
       "P18", "P35", "P38", "P40", "P41")

nr <- c("P1", "P34", "P16", "P26")

# Assign group to each sample in matrix
group <- ifelse(colnames(counts) %in% r, "R",
                ifelse(colnames(counts) %in% nr, "NR", NA))

# Convert to factor
group <- factor(group, levels = c("NR", "R"))

# Confirm that everything is correct
table(group)

# Filter only columns with assigned group
counts_filtered <- counts[, !is.na(group)]
group_filtered <- droplevels(group[!is.na(group)])





### Step 3. Differential expression analysis with DESeq2 ###

dds <- DESeqDataSetFromMatrix(countData = round(counts_filtered),
                              colData = data.frame(group = group_filtered),
                              design = ~ group)

dds <- DESeq(dds)
# We define the contrast to compare r (R) against Non-r (NR).
# The 'stat' statistic generated by DESeq2 will have positive values for genes more expressed in r,
# and negative values for genes more expressed in Non-r.
res <- results(dds, contrast = c("group", "R", "NR")) 
resOrdered <- res[order(res$pvalue), ]
res_df <- as.data.frame(resOrdered)

# Clean Ensembl IDs by removing version (e.g., ENSG00000123456.12 → ENSG00000123456)
ensembl_clean <- gsub("\\..*", "", rownames(res_df))

# Map Ensembl IDs to gene symbols using org.Hs.eg.db
res_df$symbol <- mapIds(org.Hs.eg.db,
                        keys = ensembl_clean,
                        column = "SYMBOL",
                        keytype = "ENSEMBL",
                        multiVals = "first")

# Check
head(res_df$symbol)

# Save results
write.csv(res_df, "analisis_1/DESeq2_results_R_vs_NR.csv")





### Step 4. PCA ### 
# PCA with unnormalized data
# Log2-transform raw data with +1 pseudocount
log_counts <- log2(counts_filtered + 1)

# Transpose matrix so rows are samples and columns are genes
pca_input <- t(log_counts)

# Filter genes with variance greater than 0 to avoid error in prcomp
var_genes <- apply(pca_input, 2, var)
pca_input_filtered <- pca_input[, var_genes > 0]

# Perform PCA with prcomp, centering and scaling data
pca_raw <- prcomp(pca_input_filtered, center = TRUE, scale. = TRUE)

# Create data.frame for ggplot with PC1, PC2, group, and sample name
pca_df_raw <- data.frame(
  PC1 = pca_raw$x[, 1],
  PC2 = pca_raw$x[, 2],
  Group = group_filtered,
  SampleID = rownames(pca_raw$x)
)

# Create PCA plot with ggplot2
p <- ggplot(pca_df_raw, aes(x = PC1, y = PC2, color = Group)) +
  geom_point(size = 3) +
  labs(title = "PCA - Log2 Counts (unnormalized DESeq2)", x = "PC1", y = "PC2") +
  theme_minimal()

# Display plot on screen
print(p)

# Save plot as PNG
ggsave(filename = "analisis_1/PCA_raw_counts.png", plot = p, width = 7, height = 6, dpi = 300)


# Calculate explained variance per component (example with pca_raw)
var_explained_raw <- (pca_raw$sdev)^2 / sum(pca_raw$sdev^2) * 100

# Create data.frame with explained and cumulative variance
df_var_raw <- data.frame(
  PC = paste0("PC", 1:length(var_explained_raw)),
  Var = var_explained_raw,
  Var_acum = cumsum(var_explained_raw)
)

# Create cumulative variance plot
var_plot_raw <- ggplot(df_var_raw, aes(x = seq_along(Var), y = Var_acum)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 80, linetype = "dashed", color = "red") +
  labs(title = "Cumulative variance - PCA (unnormalized)",
       x = "Principal components",
       y = "Cumulative variance (%)") +
  theme_minimal()

# Display plot on screen
print(var_plot_raw)

# Save plot as PNG
ggsave(
  filename = "analisis_1/Varianza_acumulada_raw.png",
  plot = var_plot_raw,
  width = 7,
  height = 6,
  dpi = 300
)



# PCA with normalized data
# Obtain normalized data (adjust according to your object, here is an example with DESeq2)
normalized_counts <- counts(dds, normalized = TRUE)

# If desired, perform log2-transformation with pseudocount (optional)
log_norm_counts <- log2(normalized_counts + 1)

# Transpose matrix so rows are samples and columns are genes
pca_input <- t(log_norm_counts)

# Filter genes with variance greater than 0 to avoid error in prcomp
var_genes <- apply(pca_input, 2, var)
pca_input_filtered <- pca_input[, var_genes > 0]

# Perform PCA with prcomp, centering and scaling data
pca_norm <- prcomp(pca_input_filtered, center = TRUE, scale. = TRUE)

# Create data.frame for ggplot with PC1, PC2, group, and sample name
pca_df_norm <- data.frame(
  PC1 = pca_norm$x[, 1],
  PC2 = pca_norm$x[, 2],
  Group = group_filtered,
  SampleID = rownames(pca_norm$x)
)

# Create PCA plot with ggplot2
p <- ggplot(pca_df_norm, aes(x = PC1, y = PC2, color = Group)) +
  geom_point(size = 3) +
  labs(title = "PCA - Normalized Data", x = "PC1", y = "PC2") +
  theme_minimal()

# Display plot on screen
print(p)

# Save plot as PNG
ggsave(filename = "analisis_1/PCA_normalized_counts.png", plot = p, width = 7, height = 6, dpi = 300)

# Calculate explained variance per component (normalized data)
var_explained_norm <- (pca_norm$sdev)^2 / sum(pca_norm$sdev^2) * 100

# Create data.frame with explained and cumulative variance
df_var_norm <- data.frame(
  PC = paste0("PC", 1:length(var_explained_norm)),
  Var = var_explained_norm,
  Var_acum = cumsum(var_explained_norm)
)

# Create cumulative variance plot with line at 80%
var_plot_norm <- ggplot(df_var_norm, aes(x = seq_along(Var), y = Var_acum)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 80, linetype = "dashed", color = "red") +
  labs(title = "Cumulative variance - PCA (normalized)",
       x = "Principal components",
       y = "Cumulative variance (%)") +
  theme_minimal()

# Display plot on screen
print(var_plot_norm)

# Save plot as PNG
ggsave(
  filename = "analisis_1/Varianza_acumulada_norm.png",
  plot = var_plot_norm,
  width = 7,
  height = 6,
  dpi = 300
)





### Step 5. GSEA with requested gene sets ###

# First, filter genes with valid statistic. Prepare ranking for fgsea
res_ranking <- res_df %>%
  filter(!is.na(stat), !is.na(symbol)) %>%      # remove genes with NA
  distinct(symbol, .keep_all = TRUE) %>%        # avoid duplicate names. OK for fgsea, but to keep all unique genes for downstream or reporting, you could save the table before distinct.
  arrange(desc(stat)) %>%
  select(symbol, stat) %>%
  deframe()

message("Genes in ranking: ", length(res_ranking))


# Read Excel files with our gene sets
# RNA-seq
rna <- read.xlsx("RNA.xlsx", colNames = TRUE)
rna_genes <- na.omit(rna$gene_Symbol)
rna_genes_filtered <- intersect(unique(rna_genes), names(res_ranking))
message("RNA genes: ", length(rna_genes), 
        " | In ranking: ", length(rna_genes_filtered))

# Filter genes with sufficiently high magnitude stat (more informative)
rna_genes_filtered_small <- rna_genes_filtered[abs(res_ranking[rna_genes_filtered]) > 1]
length(rna_genes_filtered_small)


# scRNA-seq
scrna <- read.xlsx("scRNA.xlsx", colNames = TRUE)
scrna_genes <- na.omit(scrna$gene)
scrna_genes_filtered <- intersect(unique(scrna_genes), names(res_ranking))
message("scRNA genes: ", length(scrna_genes), 
        " | In ranking: ", length(scrna_genes_filtered))

# Read GO gene set
xml_go <- read_xml("GO.xml")
geneset_go <- xml_attr(xml_children(xml_go)[[1]], "MEMBERS_SYMBOLIZED") %>%
  strsplit(",") %>% unlist() %>% trimws()
geneset_go_filtered <- intersect(unique(geneset_go), names(res_ranking))
message("GO gene set: ", length(geneset_go), 
        " | In ranking: ", length(geneset_go_filtered))


# Run fgsea 
set.seed(1234)

fgsea_rna <- fgsea(pathways = list(RNA = rna_genes_filtered),   # Odd results occur here because size is very large (1843)
                   stats = res_ranking)
# Warning indicates p-values could not be calculated properly for RNA set because values are "unbalanced" (positive and negative). Therefore we do:

# Run fgseaMultilevel with reduced set and appropriate parameters
fgsea_rna_small <- fgsea(
  pathways = list(RNA = rna_genes_filtered_small),
  stats = res_ranking,
  minSize = 15,
  maxSize = 1000,  # or higher if needed
  nPermSimple = 10000
)

# This seems to yield better results

fgsea_scrna <- fgsea(pathways = list(scRNA = scrna_genes_filtered),
                     stats = res_ranking)

fgsea_go <- fgsea(pathways = list(GO = geneset_go_filtered),
                  stats = res_ranking)


# View sorted results:
fgsea_go[order(padj)]
fgsea_scrna[order(padj)]
fgsea_rna[order(padj)]
fgsea_rna_small[order(padj)]






# Step 6. Enrichment plots, NES barplots, and Heatmap ###
# We use original sets in plotEnrichment because it ignores genes outside the ranking,
# but for fgsea we filter to avoid errors with absent genes.

# Enrichment plots
png("analisis_1/plotEnrichment_rna.png", width = 800, height = 600)
print(plotEnrichment(rna_genes, res_ranking) + 
        ggtitle("RNA"))
dev.off()

png("analisis_1/plotEnrichment_scrna.png", width = 800, height = 600)
print(plotEnrichment(scrna_genes, res_ranking) + 
        ggtitle("scRNA"))
dev.off()

png("analisis_1/plotEnrichment_go.png", width = 800, height = 600)
print(plotEnrichment(geneset_go, res_ranking) + 
        ggtitle("GO"))
dev.off()


# NES Barplot 
nes_df <- bind_rows(
  fgsea_rna %>% select(pathway, NES, padj),
  fgsea_scrna %>% select(pathway, NES, padj),
  fgsea_go %>% select(pathway, NES, padj),
  fgsea_rna_small %>% select(pathway, NES, padj)
)

nes_df$label <- paste0(nes_df$pathway, "\n(padj=", signif(nes_df$padj, 2), ")")
nes_df$label <- factor(nes_df$label, levels = nes_df$label[order(nes_df$NES)])

barplot_nes <- ggplot(nes_df, aes(x = label, y = NES, fill = pathway)) +
  geom_bar(stat = "identity", width = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray40") +
  labs(title = "NES Comparison (Normalized Enrichment Score)",
       y = "NES", x = "") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")

ggsave("analisis_1/barplot_nes.png", plot = barplot_nes, width = 8, height = 6, dpi = 300)


# Heatmap
plot_heatmap_for_geneset <- function(geneset, counts, res_df, group_filtered, filename, title) {
  # Filter genes present in results and counts
  genes_to_plot <- intersect(geneset, res_df$symbol)
  
  # Extract expression for those genes and transform
  mat <- log2(counts + 1)
  mat <- mat[match(genes_to_plot, res_df$symbol), ]
  mat <- t(scale(t(mat)))            # Scale by row
  mat <- mat[complete.cases(mat), ] # Filter rows with NA/NaN
  
  # Ensure names in group_filtered
  if (is.null(names(group_filtered))) {
    names(group_filtered) <- colnames(mat)
  }
  
  # Create data frame for annotation, with column names as rows
  anno_df <- data.frame(Group = group_filtered)
  rownames(anno_df) <- colnames(mat)
  anno_df$Group <- ifelse(grepl("^NR", anno_df$Group), "NR", "R")
  
  # Enforce order NR -> R and reorder columns
  anno_df$Group <- factor(anno_df$Group, levels = c("NR", "R"))
  ordered_cols <- order(anno_df$Group)
  mat <- mat[, ordered_cols]
  anno_df <- anno_df[ordered_cols, , drop = FALSE]
  
  # Save heatmap
  png(filename, width = 900, height = 800)
  pheatmap(mat,
           annotation_col = anno_df,
           show_rownames = FALSE,
           cluster_cols = FALSE,
           cluster_rows = TRUE, 
           main = title)
  dev.off()
}

# Then call for each gene set:
plot_heatmap_for_geneset(rna_genes, counts_filtered, res_df, group_filtered, "analisis_1/heatmap_rna.png", "Heatmap: RNA")
plot_heatmap_for_geneset(scrna_genes, counts_filtered, res_df, group_filtered, "analisis_1/heatmap_scrna.png", "Heatmap: scRNA")
plot_heatmap_for_geneset(geneset_go, counts_filtered, res_df, group_filtered, "analisis_1/heatmap_go.png", "Heatmap: GO")




# DESeq2 Heatmap (complete)
geneset_deseq2 <- res_df %>%
  filter(!is.na(symbol), !is.na(padj), padj < 0.05) %>%
  arrange(padj) %>%
  pull(symbol)

# Option B: top 500 by |log2FoldChange| (recommended if too many)

plot_heatmap_for_geneset(geneset_deseq2, counts_filtered, res_df, group_filtered,
                         "analisis_1/heatmap_deseq2_completo.png", "Heatmap: DESeq2 (all significant genes)")




# GSEA Table Plot: Visualizes multiple gene sets with their enrichment profiles in a single figure
# Merge results into a single data.frame
fgsea_combined <- bind_rows(
  fgsea_go,
  fgsea_scrna,
  fgsea_rna_small
)

# Define list of pathways present in combined object
pathways_list <- list(
  "GO" = geneset_go_filtered,
  "scRNA" = scrna_genes_filtered,
  "RNA" = rna_genes_filtered_small
)

# Create GSEA Table Plot
png("analisis_1/gsea_table_plot.png", width = 1200, height = 800)
plotGseaTable(pathways_list, res_ranking, fgsea_combined, gseaParam = 1)
dev.off()




### Step 7. PCA with subgroups ### 
clinical_subgroups <- c(
  "P3" = "R_PR", "P5" = "R_PR", "P27" = "R_PR",
  "P31" = "R_PR", "P32" = "R_PR", "P36" = "R_PR",
  "P18" = "R_CR", "P35" = "R_CR", "P38" = "R_CR",
  "P40" = "R_CR", "P41" = "R_CR",
  "P1" = "NR_SD", "P34" = "NR_SD",
  "P16" = "NR_PD", "P26" = "NR_PD"
)


# PCA with unnormalized data
# Log2-transform raw data with +1 pseudocount
log_counts <- log2(counts_filtered + 1)

# Transpose matrix so rows are samples and columns are genes
pca_input <- t(log_counts)

# Filter genes with variance greater than 0 (avoid error in prcomp)
var_genes <- apply(pca_input, 2, var)
pca_input_filtered <- pca_input[, var_genes > 0]

# Perform PCA with prcomp, centering and scaling data
pca_raw <- prcomp(pca_input_filtered, center = TRUE, scale. = TRUE)

# Create data.frame for ggplot with PC1, PC2, clinical group, and sample name
pca_df_raw <- data.frame(
  PC1 = pca_raw$x[, 1],
  PC2 = pca_raw$x[, 2],
  Group = clinical_subgroups[rownames(pca_raw$x)],
  SampleID = rownames(pca_raw$x)
)

# PCA plot
p_raw <- ggplot(pca_df_raw, aes(x = PC1, y = PC2, color = Group, label = SampleID)) +
  geom_point(size = 3) +
  geom_text(vjust = -1.2, size = 3) +  # Optional labels
  labs(title = "PCA - Log2 Counts (unnormalized)", x = "PC1", y = "PC2") +
  theme_minimal()

# Display plot
print(p_raw)

# Save plot
ggsave(filename = "analisis_1/PCA_raw_clinical.png", plot = p_raw, width = 7, height = 6, dpi = 300)

# Version with facets by clinical group
p_raw_faceted <- p_raw + facet_wrap(~Group)
ggsave(filename = "analisis_1/PCA_raw_clinical_faceted.png", plot = p_raw_faceted, width = 9, height = 6, dpi = 300)


# PCA with normalized data

# Obtain normalized data (example with DESeq2)
normalized_counts <- counts(dds, normalized = TRUE)

# Log2-transform normalized data with +1 pseudocount
log_norm_counts <- log2(normalized_counts + 1)

# Transpose matrix so rows are samples and columns are genes
pca_input <- t(log_norm_counts)

# Filter genes with variance greater than 0
var_genes <- apply(pca_input, 2, var)
pca_input_filtered <- pca_input[, var_genes > 0]

# Perform PCA
pca_norm <- prcomp(pca_input_filtered, center = TRUE, scale. = TRUE)

# Create data.frame for ggplot with PC1, PC2, clinical group, and sample name
pca_df_norm <- data.frame(
  PC1 = pca_norm$x[, 1],
  PC2 = pca_norm$x[, 2],
  Group = clinical_subgroups[rownames(pca_norm$x)],
  SampleID = rownames(pca_norm$x)
)

# PCA plot
p_norm <- ggplot(pca_df_norm, aes(x = PC1, y = PC2, color = Group, label = SampleID)) +
  geom_point(size = 3) +
  geom_text(vjust = -1.2, size = 3) +
  labs(title = "PCA - Normalized Data (Clinical Groups)", x = "PC1", y = "PC2") +
  theme_minimal()

# Display plot
print(p_norm)

# Save plot
ggsave(filename = "analisis_1/PCA_normalized_clinical.png", plot = p_norm, width = 7, height = 6, dpi = 300)

# Version with facets by clinical group
p_norm_faceted <- p_norm + facet_wrap(~Group)
ggsave(filename = "analisis_1/PCA_normalized_clinical_faceted.png", plot = p_norm_faceted, width = 9, height = 6, dpi = 300)





### Step 8. Volcano plots ### 
# Ensure correct order for specific groups
combined_group <- factor(clinical_subgroups[colnames(counts_filtered)])
table(combined_group)

# Dataset for multiple comparisons (conditions)
dds_combined <- DESeqDataSetFromMatrix(countData = round(counts_filtered),
                                       colData = data.frame(condition = combined_group),
                                       design = ~ condition)
dds_combined <- DESeq(dds_combined)  # Run DESeq for dds_combined

# Create factor simplified for comparison R vs NR
group <- factor(clinical_subgroups[colnames(counts_filtered)])
group_simple <- ifelse(group %in% c("R_CR", "R_PR"), "R", "NR")
group_simple <- factor(group_simple, levels = c("NR", "R"))

# Create dds object with simplified factor
dds <- DESeqDataSetFromMatrix(countData = round(counts_filtered),
                              colData = data.frame(group_simple = group_simple),
                              design = ~ group_simple)
dds <- DESeq(dds)


# Define comparisons, using "group_simple" for R_vs_NR
comparisons <- list(
  NR_SD_vs_R_PR = list(dds = dds_combined, factor = "condition", level1 = "R_PR", level2 = "NR_SD"),
  NR_SD_vs_R_CR = list(dds = dds_combined, factor = "condition", level1 = "R_CR", level2 = "NR_SD"),
  NR_PD_vs_R_PR = list(dds = dds_combined, factor = "condition", level1 = "R_PR", level2 = "NR_PD"),
  NR_PD_vs_R_CR = list(dds = dds_combined, factor = "condition", level1 = "R_CR", level2 = "NR_PD"),
  R_vs_NR = list(dds = dds, factor = "group_simple", level1 = "R", level2 = "NR")
)

# Loop identical
for (name in names(comparisons)) {
  comp <- comparisons[[name]]
  
  dds_obj <- comp$dds
  comp_factor <- comp$factor
  comp_lvl1 <- comp$level1
  comp_lvl2 <- comp$level2
  
  colData(dds_obj)[[comp_factor]] <- factor(colData(dds_obj)[[comp_factor]])
  
  res <- results(dds_obj, contrast = c(comp_factor, comp_lvl1, comp_lvl2))
  res <- res[!is.na(res$padj), ]
  
  ensembl_ids <- gsub("\\..*$", "", rownames(res))
  
  gene_symbols_list <- mapIds(org.Hs.eg.db,
                              keys = ensembl_ids,
                              column = "SYMBOL",
                              keytype = "ENSEMBL",
                              multiVals = "list")
  
  gene_symbols <- sapply(gene_symbols_list, function(x) if(length(x) > 0) x[1] else NA)
  
  res$symbol <- gene_symbols
  
  p <- EnhancedVolcano(res,
                       lab = res$symbol,
                       x = 'log2FoldChange',
                       y = 'padj',
                       pCutoff = 0.05,
                       FCcutoff = 1,
                       title = paste("Volcano:", gsub("_vs_", " vs ", name)),
                       labSize = 4)
  
  ggsave(filename = paste0("analisis_1/volcano_", name, ".png"), plot = p, width = 8, height = 6, dpi = 300)
  cat("Volcano saved to:", paste0("volcano_", name, ".png"), "\n")
}





### Step 9. GO Enrichment ###

# Prepare significant genes (adjust cutoff criteria if desired)
genes_sig <- res_df %>%
  filter(!is.na(symbol), padj < 0.05) %>%
  pull(symbol)

# Also gene universe (all genes tested in DESeq2 with valid symbols)
gene_universe <- na.omit(res_df$symbol)

# Function to run enrichGO by ontology and export
run_go_enrichment <- function(ontology, genes, universe, out_prefix) {
  ego <- enrichGO(
    gene          = genes,
    universe      = universe,
    OrgDb         = org.Hs.eg.db,
    keyType       = "SYMBOL",
    ont           = ontology,
    pAdjustMethod = "BH",
    pvalueCutoff  = 0.05,
    qvalueCutoff  = 0.2,
    readable      = TRUE
  )
  
  # Create foldChange vector for significant genes used in enrichGO
  gene_fc <- res_df %>%
    filter(symbol %in% genes) %>%
    select(symbol, log2FoldChange) %>%
    deframe()
  
  # Save results table
  out_file <- paste0(out_prefix, "_", ontology, "_enrichment.xlsx")
  write.xlsx(as.data.frame(ego), out_file, overwrite = TRUE)
  
  # Barplot
  png(paste0(out_prefix, "_", ontology, "_barplot.png"), width = 1200, height = 900)
  print(barplot(ego, showCategory = 15, title = paste("GO", ontology, "Barplot")))
  dev.off()
  
  # Dotplot
  png(paste0(out_prefix, "_", ontology, "_dotplot.png"), width = 1200, height = 900)
  print(dotplot(ego, showCategory = 15, title = paste("GO", ontology, "Dotplot")))
  dev.off()
  
  # Cnetplot with foldChange to color genes
  png(paste0(out_prefix, "_", ontology, "_cnetplot.png"), width = 1200, height = 900)
  print(
    cnetplot(ego, 
             showCategory = 15, 
             foldChange = gene_fc, 
             title = paste("GO", ontology, "Cnetplot")) + 
      scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) 
  )
  dev.off()
  
  return(ego)
}

# Run for BP, MF, and CC
ego_bp <- run_go_enrichment("BP", genes_sig, gene_universe, "analisis_1/GO_BP_results")
ego_mf <- run_go_enrichment("MF", genes_sig, gene_universe, "analisis_1/GO_MF_results")
ego_cc <- run_go_enrichment("CC", genes_sig, gene_universe, "analisis_1/GO_CC_results")





### Step 10. KEGG ### 

# Prepare significant genes (conversion to Entrez) 
genes_sig <- res_df %>%
  filter(!is.na(symbol), padj < 0.05) %>%
  pull(symbol)

# Map symbols to Entrez IDs
gene_entrez <- mapIds(org.Hs.eg.db,
                      keys = genes_sig,
                      column = "ENTREZID",
                      keytype = "SYMBOL",
                      multiVals = "first")

gene_entrez <- na.omit(gene_entrez)  # remove NAs

# Function for KEGG enrichment 
run_kegg_enrichment <- function(gene_entrez, out_prefix) {
  ekegg <- enrichKEGG(gene = gene_entrez,
                      organism = "hsa",
                      pvalueCutoff = 0.05)
  
  # Convert to readable gene symbols
  ekegg <- setReadable(ekegg, OrgDb = org.Hs.eg.db, keyType = "ENTREZID")
  
  # Create foldChange vector with EntrezID names and log2FC values
  gene_info <- res_df %>%
    filter(symbol %in% genes_sig) %>%
    select(symbol, log2FoldChange) %>%
    mutate(ENTREZID = mapIds(org.Hs.eg.db,
                             keys = symbol,
                             column = "ENTREZID",
                             keytype = "SYMBOL",
                             multiVals = "first")) %>%
    filter(!is.na(ENTREZID))
  
  gene_fc <- gene_info$log2FoldChange
  names(gene_fc) <- gene_info$ENTREZID
  
  # Export results
  out_file <- paste0(out_prefix, "_KEGG_enrichment.xlsx")
  write.xlsx(as.data.frame(ekegg), out_file, overwrite = TRUE)
  
  # Plots
  png(paste0(out_prefix, "_KEGG_dotplot.png"), width = 1200, height = 900)
  print(dotplot(ekegg, showCategory = 15, title = "KEGG Dotplot"))
  dev.off()
  
  png(paste0(out_prefix, "_KEGG_barplot.png"), width = 1200, height = 900)
  print(barplot(ekegg, showCategory = 15, title = "KEGG Barplot"))
  dev.off()
  
  png(paste0(out_prefix, "_KEGG_cnetplot.png"), width = 1200, height = 900)
  print(
    cnetplot(ekegg,
             showCategory = 15,
             circular = TRUE,
             colorEdge = TRUE,
             foldChange = gene_fc) +
      scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)
  )
  dev.off()
  
  return(ekegg)
}

# Run 
ekegg_results <- run_kegg_enrichment(gene_entrez, "analisis_1/KEGG_results")





### Brief interpretation following results analysis ### (may need expansion after running GSEA Table Plot and subsequent steps) ###############################

# FGSEA analysis results demonstrate strong and significant enrichment
# in gene sets corresponding to the GO pathway (Cellular response to bacterial molecules)
# and the scRNA set, with extremely low adjusted p-values (padj < 5e-15 and < 2.5e-32, respectively)
# and high positive NES (>2.2 and >2.3), indicating a consistent over-representation
# of upregulated genes in these pathways within the ranking, associated with the R condition.
# 
# In contrast, the original RNA set exhibits issues in p-value calculation (NA),
# likely due to the very large size and lack of variability in gene statistics.
# However, filtering the RNA set to include only genes with stronger effects (rna_genes_filtered_small)
# yields a significant result with a negative NES (≈ -2), suggesting that this subpopulation of genes
# is enriched in the opposite condition, i.e., overexpressed in Non-r.
#
# This highlights the importance of tuning parameters and appropriately filtering gene sets
# to obtain reliable and biologically interpretable results in FGSEA, enabling the detection
# of clear differences in gene expression associated with different responses.






# Analysis 2. R vs NR comparison using top X genes (applies only to RNA_seq)

### Step 1. GSEA with requested gene set ###

# First filter genes with valid statistic. Prepare ranking for fgsea. In principle already done previously

# Read Excel file of our gene set
# RNA-seq (selecting top X based on LFC)
rna_top <- read.xlsx("RNA.xlsx", colNames = TRUE)
rna_top <- rna_top %>%
  filter(!is.na(LFC_highvs_low)) %>%
  mutate(abs_LFC = abs(LFC_highvs_low)) %>%
  arrange(desc(abs_LFC))

topX_rna <- head(rna_top$gene_Symbol, X)
rna_genes_top_filtered <- intersect(unique(topX_rna), names(res_ranking))
message("RNA genes total: ", length(topX_rna),
        " | In DESeq2 ranking: ", length(rna_genes_top_filtered))

# Optional: Filter genes with sufficiently high magnitude stat (more informative)
rna_genes_filtered_topsmall <- rna_genes_top_filtered[abs(res_ranking[rna_genes_top_filtered]) > 1]
length(rna_genes_filtered_topsmall)


# Run fgsea 
set.seed(1234)

fgsea_rna_top <- fgsea(pathways = list(RNA = rna_genes_top_filtered),
                       stats = res_ranking)
# Warning indicates p-values could not be calculated properly for RNA set because values are "unbalanced" (positive and negative). Therefore we do:

# Run fgseaMultilevel with reduced set and appropriate parameters
fgsea_rna_topsmall <- fgsea(
  pathways = list(RNA = rna_genes_filtered_topsmall),
  stats = res_ranking,
  minSize = 15,
  maxSize = 1000,
  nPermSimple = 10000
)


# View sorted results:
fgsea_rna_top[order(padj)]
fgsea_rna_topsmall[order(padj)]



# Step 2. Enrichment plots, NES barplots, and Heatmap ###

# Enrichment plots
png("analisis_2/plotEnrichment_rna_top.png", width = 800, height = 600)
print(plotEnrichment(rna_genes_top_filtered, res_ranking) + 
        ggtitle("RNA-seq top X"))
dev.off()

png("analisis_2/plotEnrichment_rna_topsmall.png", width = 800, height = 600)
print(plotEnrichment(rna_genes_filtered_topsmall, res_ranking) + 
        ggtitle("small RNA-seq top X"))
dev.off()



# NES Barplot 

# Rename pathways to match
fgsea_rna_topsmall$pathway <- "RNA_topsmall"
fgsea_rna_top$pathway      <- "RNA_top"

nes_df_top <- bind_rows(
  fgsea_rna_top %>% select(pathway, NES, padj),
  fgsea_rna_topsmall %>% select(pathway, NES, padj),
  fgsea_go %>% select(pathway, NES, padj),
  fgsea_scrna %>% select(pathway, NES, padj)
)

nes_df_top$label <- paste0(nes_df_top$pathway, "\n(padj=", signif(nes_df_top$padj, 2), ")")
nes_df_top$label <- factor(nes_df_top$label, levels = nes_df_top$label[order(nes_df_top$NES)])

barplot_nes_top <- ggplot(nes_df_top, aes(x = label, y = NES, fill = pathway)) +
  geom_bar(stat = "identity", width = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray40") +
  labs(title = "NES Comparison (Normalized Enrichment Score)",
       y = "NES", x = "") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")

ggsave("analisis_2/barplot_nes_top.png", plot = barplot_nes_top, width = 8, height = 6, dpi = 300)


# Heatmap using plot_heatmap_for_geneset previously defined

# For this case, we do the following:
plot_heatmap_for_geneset(topX_rna, counts_filtered, res_df, group_filtered, "analisis_2/heatmap_rna_top.png", "Heatmap: Top RNA")



# GSEA Table Plot: Visualizes multiple gene sets with their enrichment profiles in a single figure
# Merge results into a single data.frame
fgsea_combined_top <- bind_rows(
  fgsea_go,
  fgsea_scrna,
  fgsea_rna_topsmall,
  fgsea_rna_top
)

# Define list of pathways present in combined object
pathways_list_top <- list(
  "GO" = geneset_go_filtered,
  "scRNA" = scrna_genes_filtered,
  "RNA_topsmall" = rna_genes_filtered_topsmall,
  "RNA_top" = rna_genes_top_filtered
)

# Create GSEA Table Plot
png("analisis_2/gsea_table_plot_top.png", width = 1200, height = 800)
plotGseaTable(pathways_list_top, res_ranking, fgsea_combined_top, gseaParam = 1)
dev.off()












### Analysis 3. Comparison R/CR vs R/PR


## Step 1. Libraries
library(limma)
library(sva)


### Step 2. PCAs

# Define new groups
R_CR <- c("P18", "P35", "P38", "P40", "P41")
R_PR <- c("P3", "P5", "P27", "P32", "P36")

# Assign group to each sample
group2 <- ifelse(colnames(counts) %in% R_CR, "R_CR",
                ifelse(colnames(counts) %in% R_PR, "R_PR", NA))

# Convert to factor with levels in correct order
group2 <- factor(group2, levels = c("R_PR", "R_CR"))

# Filter removing P31 and NA
keep_samples2 <- !is.na(group2)
counts_filtered2 <- counts[, keep_samples2]
group_filtered2 <- droplevels(group2[keep_samples2])

# Verify
colnames(counts_filtered2)
group_filtered2
length(group_filtered2)


## PCA with normalized data (R_PR vs R_CR) ###

# Normalize with DESeq2
dds2 <- DESeqDataSetFromMatrix(countData = round(counts_filtered2),
                              colData = data.frame(group = group_filtered2),
                              design = ~ group)
dds2 <- DESeq(dds2)

# Obtain normalized data
normalized_counts2 <- counts(dds2, normalized = TRUE)

# Log2-transformation with pseudocount
log_norm_counts2 <- log2(normalized_counts2 + 1)

# ------------------ HELPER FUNCTIONS ------------------ #

# Function for PCA
do_pca <- function(data_matrix, groups, title, file_name) {
  # Validate dimensions
  stopifnot(ncol(data_matrix) == length(groups))
  
  # Prepare data for PCA
  pca_input <- t(data_matrix)
  var_genes <- apply(pca_input, 2, var)
  pca_input_filtered <- pca_input[, var_genes > 0]
  pca <- prcomp(pca_input_filtered, center = TRUE, scale. = TRUE)
  
  # Create dataframe for plot
  pca_df <- data.frame(
    PC1 = pca$x[, 1],
    PC2 = pca$x[, 2],
    Group = groups,
    SampleID = rownames(pca$x)
  )
  
  # PCA plot
  p <- ggplot(pca_df, aes(x = PC1, y = PC2, color = Group, label = SampleID)) +
    geom_point(size = 3) +
    geom_text(vjust = -0.5, size = 3) +
    labs(title = title, x = "PC1", y = "PC2") +
    theme_minimal()
  print(p)
  ggsave(
    filename = paste0("analisis_3/", file_name),
    plot = p, width = 7, height = 6, dpi = 300
  )
  
  # Cumulative variance
  var_explained <- (pca$sdev)^2 / sum(pca$sdev^2) * 100
  df_var <- data.frame(
    PC = paste0("PC", 1:length(var_explained)),
    Var = var_explained,
    Var_acum = cumsum(var_explained)
  )
  
  var_plot <- ggplot(df_var, aes(x = seq_along(Var), y = Var_acum)) +
    geom_line() +
    geom_point() +
    geom_hline(yintercept = 80, linetype = "dashed", color = "red") +
    labs(title = paste("Cumulative variance -", title),
         x = "Principal components",
         y = "Cumulative variance (%)") +
    theme_minimal()
  
  print(var_plot)
  ggsave(filename = paste0("analisis_3/Varianza_", file_name),
         plot = var_plot, width = 7, height = 6, dpi = 300)
}

# ------------------ 1) UNADJUSTED PCA ------------------ #
do_pca(log_norm_counts2, group_filtered2,
       "Unadjusted PCA - R_PR vs R_CR",
       "PCA_sin_correccion_RPR_vs_RCR.png")

# ------------------ 2) PCA with removeBatchEffect ------------------ #
batch_remove <- ifelse(colnames(log_norm_counts2) %in% c("P3", "P32"), "Batch2", "Batch1")
log_rbe <- removeBatchEffect(log_norm_counts2, batch = batch_remove,
                             design = model.matrix(~ group_filtered2))
do_pca(log_rbe, group_filtered2,
       "PCA with removeBatchEffect - R_PR vs R_CR",
       "PCA_removeBatchEffect_RPR_vs_RCR.png")

# ------------------ 3) PCA with ComBat ------------------ #
batch_combat <- ifelse(colnames(log_norm_counts2) %in% c("P3", "P32"), "Batch2", "Batch1")
mod_combat <- model.matrix(~ group_filtered2)
combat_corrected <- ComBat(dat = log_norm_counts2, batch = batch_combat,
                           mod = mod_combat, par.prior = TRUE)
do_pca(combat_corrected, group_filtered2,
       "PCA with ComBat - R_PR vs R_CR",
       "PCA_ComBat_RPR_vs_RCR.png")



### Step 3. Differential expression analysis with DESeq2 ###

# dds is already created in PCA
# Contrast: R_CR vs R_PR
res2 <- results(dds2, contrast = c("group", "R_CR", "R_PR"))
res2 <- res2[!is.na(res2$padj), ]  # filter NAs in padj

# Clean IDs
ensembl_clean2 <- gsub("\\..*$", "", rownames(res2))

# Convert to dataframe
res_df2 <- as.data.frame(res2)

# Map symbols
res_df2$symbol <- mapIds(org.Hs.eg.db,
                        keys = ensembl_clean2,
                        column = "SYMBOL",
                        keytype = "ENSEMBL",
                        multiVals = "first")

# Save results
write.csv(res_df2, "analisis_3/DESeq2_results_RCR_vs_RPR.csv")

# Prepare ranking for GSEA
res_ranking2 <- res_df2 %>%
  filter(!is.na(stat), !is.na(symbol)) %>%
  distinct(symbol, .keep_all = TRUE) %>%
  arrange(desc(stat)) %>%
  select(symbol, stat) %>%
  deframe()

message("Genes in ranking: ", length(res_ranking2))



## Read gene sets and select top X genes by fold change

# RNA-seq: read Excel and select top X genes by absolute LFC
rna <- read.xlsx("RNA.xlsx", colNames = TRUE)
rna <- rna %>%
  filter(!is.na(LFC_highvs_low)) %>%
  mutate(abs_LFC = abs(LFC_highvs_low)) %>%
  arrange(desc(abs_LFC))

topX_rna <- head(rna$gene_Symbol, X)
# Filter genes present in ranking
rna_genes_filtered2 <- intersect(unique(topX_rna), names(res_ranking2))
message("RNA genes total: ", length(topX_rna),
        " | In DESeq2 ranking: ", length(rna_genes_filtered2))


# scRNA-seq: read Excel and select top X genes by abs(avg_log2FC)
scrna <- read.xlsx("scRNA.xlsx", colNames = TRUE)
scrna <- scrna %>%
  filter(!is.na(avg_log2FC)) %>%
  mutate(abs_logFC = abs(avg_log2FC)) %>%
  arrange(desc(abs_logFC))

topX_scrna <- head(scrna$gene, X)
scrna_genes_filtered2 <- intersect(unique(topX_scrna), names(res_ranking2))
message("scRNA genes total: ", length(topX_scrna),
        " | In DESeq2 ranking: ", length(scrna_genes_filtered2))


# GO gene set: read XML and filter genes
xml_go <- read_xml("GO.xml")
geneset_go <- xml_attr(xml_children(xml_go)[[1]], "MEMBERS_SYMBOLIZED") %>%
  strsplit(",") %>% unlist() %>% trimws()
geneset_go_filtered2 <- intersect(unique(geneset_go), names(res_ranking2))
message("GO gene set total: ", length(geneset_go),
        " | In DESeq2 ranking: ", length(geneset_go_filtered2))

# Run fgsea
set.seed(1234)
fgsea_rna2 <- fgsea(pathways = list(RNA = rna_genes_filtered2),
                   stats = res_ranking2)
fgsea_scrna2 <- fgsea(pathways = list(scRNA = scrna_genes_filtered2),
                     stats = res_ranking2)
fgsea_go2 <- fgsea(pathways = list(GO = geneset_go_filtered2),
                   stats = res_ranking2)
# Results ordered by adjusted p-value
fgsea_rna2[order(padj), ]
fgsea_scrna2[order(padj), ]
fgsea_go2[order(padj), ]


### Step 4. Plots

# Enrichment plots
png("analisis_3/plotEnrichment_rna_RCRvsRPR.png", width = 800, height = 600)
print(plotEnrichment(rna_genes_filtered2, res_ranking2) + 
        ggtitle("RNA (Top X genes, R_CR vs R_PR)"))
dev.off()

png("analisis_3/plotEnrichment_scrna_RCRvsRPR.png", width = 800, height = 600)
print(plotEnrichment(scrna_genes_filtered2, res_ranking2) + 
        ggtitle("scRNA (All X genes, R_CR vs R_PR)"))
dev.off()

png("analisis_3/plotEnrichment_go_RCRvsRPR.png", width = 800, height = 600)
print(plotEnrichment(geneset_go_filtered2, res_ranking2) + 
        ggtitle("GO (R_CR vs R_PR)"))
dev.off()


# NES Barplot: removed fgsea_rna_small since small subset is no longer used
nes_df2 <- bind_rows(
  fgsea_rna2 %>% select(pathway, NES, padj),
  fgsea_scrna2 %>% select(pathway, NES, padj),
  fgsea_go2 %>% select(pathway, NES, padj)
)

nes_df2$label <- paste0(nes_df2$pathway,
                       "\nNES=", round(nes_df2$NES, 2),
                       ", padj=", signif(nes_df2$padj, 2))
nes_df2$label <- make.unique(nes_df2$label)
nes_df2$label <- factor(nes_df2$label, levels = nes_df2$label[order(nes_df2$NES)])

barplot_nes2 <- ggplot(nes_df2, aes(x = label, y = NES, fill = pathway)) +
  geom_bar(stat = "identity", width = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray40") +
  labs(title = "NES Comparison (Normalized Enrichment Score)",
       y = "NES", x = "") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")

ggsave("analisis_3/barplot_nes_RPR_vs_RCR.png", plot = barplot_nes2, width = 8, height = 6, dpi = 300)


# GSEA Table Plot with only used sets
fgsea_combined2 <- bind_rows(fgsea_go2, fgsea_scrna2, fgsea_rna2)
pathways_list2 <- list(
  "GO" = geneset_go_filtered2,
  "scRNA" = scrna_genes_filtered2,
  "RNA" = rna_genes_filtered2
)

png("analisis_3/gsea_table_RCRvsRPR.png", width = 1200, height = 800)
plotGseaTable(pathways_list2, res_ranking2, fgsea_combined2, gseaParam = 1)
dev.off()


# Heatmaps: use filtered gene sets and correct order of samples and groups
plot_heatmap_for_geneset2 <- function(geneset, counts, res_df2, group_filtered, filename, title) {
  genes_to_plot <- intersect(geneset, res_df2$symbol)
  mat <- log2(counts + 1)
  mat <- mat[match(genes_to_plot, res_df2$symbol), , drop=FALSE]
  mat <- t(scale(t(mat)))
  mat <- mat[complete.cases(mat), , drop=FALSE]
  
  # Assign names to group if missing
  if (is.null(names(group_filtered2))) names(group_filtered2) <- colnames(mat)
  anno_df <- data.frame(Group = group_filtered2)
  rownames(anno_df) <- colnames(mat)
  anno_df$Group <- factor(ifelse(anno_df$Group == "R_PR", "PR", "CR"), levels = c("PR", "CR"))
  
  ordered_cols <- order(anno_df$Group)
  mat <- mat[, ordered_cols, drop=FALSE]
  anno_df <- anno_df[ordered_cols, , drop=FALSE]
  
  png(filename, width = 900, height = 800)
  pheatmap::pheatmap(mat,
                     annotation_col = anno_df,
                     show_rownames = FALSE,
                     cluster_cols = FALSE,
                     cluster_rows = TRUE, 
                     main = title)
  dev.off()
}

plot_heatmap_for_geneset2(rna_genes_filtered2, counts_filtered2, res_df2, group_filtered2, 
                          "analisis_3/heatmap_rna_RCRvsRPR.png", "Heatmap: RNA (R_CR vs R_PR)")

plot_heatmap_for_geneset2(scrna_genes_filtered2, counts_filtered2, res_df2, group_filtered2, 
                          "analisis_3/heatmap_scrna_RCRvsRPR.png", "Heatmap: scRNA (R_CR vs R_PR)")

plot_heatmap_for_geneset2(geneset_go_filtered2, counts_filtered2, res_df2, group_filtered2, 
                          "analisis_3/heatmap_go_RCRvsRPR.png", "Heatmap: GO (R_CR vs R_PR)")

# Extract significant DESeq2 genes (padj < 0.05)
geneset_deseq2_2 <- res_df2 %>%
  filter(!is.na(symbol), !is.na(padj), padj < 0.05) %>%
  arrange(padj) %>%
  pull(symbol) %>%
  unique()  # ensure no duplicates

# Plot complete heatmap with these genes
plot_heatmap_for_geneset2(geneset_deseq2_2, counts_filtered2, res_df2, group_filtered2,
                          "analisis_3/heatmap_deseq2_completo_2.png",
                          "Heatmap: DESeq2 complete 2")

### Step 5. Volcano plots

# Define comparison R_CR vs R_PR
comparisons2 <- list(
  R_CR_vs_R_PR = list(dds = dds2, factor = "group", level1 = "R_CR", level2 = "R_PR")
)

# Loop for volcano plot
for (name in names(comparisons2)) {
  comp <- comparisons2[[name]]
  
  dds_obj <- comp$dds
  comp_factor <- comp$factor
  comp_lvl1 <- comp$level1
  comp_lvl2 <- comp$level2
  
  # Ensure factor has levels in correct order
  colData(dds_obj)[[comp_factor]] <- factor(colData(dds_obj)[[comp_factor]], levels = c(comp_lvl2, comp_lvl1))
  
  # Obtain results with contrast
  res <- results(dds_obj, contrast = c(comp_factor, comp_lvl1, comp_lvl2))
  res <- res[!is.na(res$padj), ]
  
  # Obtain gene symbols
  ensembl_ids <- gsub("\\..*$", "", rownames(res))
  gene_symbols_list <- mapIds(org.Hs.eg.db,
                              keys = ensembl_ids,
                              column = "SYMBOL",
                              keytype = "ENSEMBL",
                              multiVals = "list")
  gene_symbols <- sapply(gene_symbols_list, function(x) if(length(x) > 0) x[1] else NA)
  res$symbol <- gene_symbols
  
  # Generate volcano plot
  p <- EnhancedVolcano(res,
                       lab = res$symbol,
                       x = 'log2FoldChange',
                       y = 'padj',
                       pCutoff = 0.05,
                       FCcutoff = 1,
                       title = paste("Volcano:", gsub("_vs_", " vs ", name)),
                       labSize = 4)
  
  # Save plot
  ggsave(filename = paste0("analisis_3/volcano_", name, ".png"), plot = p, width = 8, height = 6, dpi = 300)
  cat("Volcano saved to:", paste0("volcano_", name, ".png"), "\n")
}


### Step 6. GO Enrichment

# Filter significant genes (can change padj < 0.05 if desired)
genes_sig2 <- res_df2 %>%
  filter(!is.na(symbol), padj < 0.05) %>%
  pull(symbol)

# Gene universe (all with valid symbol in your analysis)
gene_universe2 <- na.omit(res_df2$symbol)

# Function to run enrichGO by ontology and save results
run_go_enrichment2 <- function(ontology, genes, universe, out_prefix, minGS, maxGS) {
  ego <- enrichGO(
    gene          = genes,
    universe      = universe,
    OrgDb         = org.Hs.eg.db,
    keyType       = "SYMBOL",
    ont           = ontology,
    pAdjustMethod = "BH",
    pvalueCutoff  = 0.05,
    qvalueCutoff  = 0.2,
    readable      = TRUE,
    minGSSize     = minGS, # adjusted minimum gene set size to retrieve more terms
    maxGSSize     = maxGS  # adjusted maximum gene set size
  )
  
  # foldChange vector to color plots
  gene_fc <- res_df2 %>%
    filter(symbol %in% genes) %>%
    select(symbol, log2FoldChange) %>%
    deframe()
  
  # Export results table
  out_file <- paste0(out_prefix, "_", ontology, "_enrichment.xlsx")
  write.xlsx(as.data.frame(ego), out_file, overwrite = TRUE)
  
  # Create plots and save
  png(paste0(out_prefix, "_", ontology, "_barplot.png"), width = 1200, height = 900)
  print(barplot(ego, showCategory = 15, title = paste("GO", ontology, "Barplot"))+
          theme(axis.text.y = element_text(size = 14))  # increase label size
        )
  dev.off()
  
  png(paste0(out_prefix, "_", ontology, "_dotplot.png"), width = 1200, height = 900)
  print(dotplot(ego, showCategory = 15, title = paste("GO", ontology, "Dotplot"))+
          theme(axis.text.y = element_text(size = 14))  # increase label size
  )
  dev.off()
  
  png(paste0(out_prefix, "_", ontology, "_cnetplot.png"), width = 1200, height = 900)
  print(
    cnetplot(ego, showCategory = 15, foldChange = gene_fc, title = paste("GO", ontology, "Cnetplot")) +
      scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)
  )
  dev.off()
  
  return(ego)
}

# Run enrichment for the 3 GO ontologies
ego_bp <- run_go_enrichment2("BP", genes_sig2, gene_universe2, "analisis_3/GO_BP_results_2", minGS = 12, maxGS = 2000)
ego_mf <- run_go_enrichment2("MF", genes_sig2, gene_universe2, "analisis_3/GO_MF_results_2", minGS = 5,  maxGS = 1000)
ego_cc <- run_go_enrichment2("CC", genes_sig2, gene_universe2, "analisis_3/GO_CC_results_2", minGS = 8,  maxGS = 1500)



### Step 7. KEGG Enrichment
# Prepare significant genes (non-NA symbol, padj < 0.1)
genes_sig2 <- res_df2 %>%
  filter(!is.na(symbol), padj < 0.1) %>%
  pull(symbol)

# Map significant symbols to Entrez IDs for KEGG
gene_entrez2 <- mapIds(org.Hs.eg.db,
                      keys = genes_sig2,
                      column = "ENTREZID",
                      keytype = "SYMBOL",
                      multiVals = "first") %>%
  na.omit()

# Function for KEGG enrichment
run_kegg_enrichment2 <- function(gene_entrez2, out_prefix) {
  ekegg <- enrichKEGG(gene = gene_entrez2,
                      organism = "hsa",
                      pvalueCutoff = 0.05)

  # Check if results exist
  if (is.null(ekegg) || nrow(as.data.frame(ekegg)) == 0) {
    warning("No significant KEGG pathways found for these genes.")
    return(NULL)
  }
  
  # Convert to readable symbols
  ekegg <- setReadable(ekegg, OrgDb = org.Hs.eg.db, keyType = "ENTREZID")
  
  # foldChange vector with EntrezID and log2FC for cnetplot
  gene_info <- res_df2 %>%
    filter(symbol %in% genes_sig2) %>%
    select(symbol, log2FoldChange) %>%
    mutate(ENTREZID = mapIds(org.Hs.eg.db,
                             keys = symbol,
                             column = "ENTREZID",
                             keytype = "SYMBOL",
                             multiVals = "first")) %>%
    filter(!is.na(ENTREZID))
  
  gene_fc <- gene_info$log2FoldChange
  names(gene_fc) <- gene_info$ENTREZID
  
  # Save results
  out_file <- paste0(out_prefix, "_KEGG_enrichment.xlsx")
  write.xlsx(as.data.frame(ekegg), out_file, overwrite = TRUE)
  
  # Plots
  png(paste0(out_prefix, "_KEGG_dotplot.png"), width = 1200, height = 900)
  print(dotplot(ekegg, showCategory = 15, title = "KEGG Dotplot") +
          theme(axis.text.y = element_text(size = 14))
  )
  dev.off()
  
  png(paste0(out_prefix, "_KEGG_barplot.png"), width = 1200, height = 900)
  print(barplot(ekegg, showCategory = 15, title = "KEGG Barplot") +
          theme(axis.text.y = element_text(size = 14))
  )
  dev.off()
  
  png(paste0(out_prefix, "_KEGG_cnetplot.png"), width = 1200, height = 900)
  print(
    cnetplot(ekegg,
             showCategory = 15,
             circular = TRUE,
             colorEdge = TRUE,
             foldChange = gene_fc) +
      scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)
  )
  dev.off()
  
  return(ekegg)
}

# Run KEGG enrichment for R_CR vs R_PR
ekegg_results2 <- run_kegg_enrichment2(gene_entrez2, "analisis_3/KEGG_RCR_vs_RPR")







### PCA with CPM and TPM from raw data ##########
# Libraries
library(edgeR)
library(biomaRt)


# ---- Step 1. Obtain gene lengths ----
ensembl_ids <- gsub("\\..*", "", rownames(counts_filtered2))  # Strip ID version

mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

gene_annotations <- getBM(
  attributes = c("ensembl_gene_id", "transcript_length"),
  filters = "ensembl_gene_id",
  values = ensembl_ids,
  mart = mart
)

# Calculate average length per gene
gene_length_avg <- aggregate(transcript_length ~ ensembl_gene_id, gene_annotations, mean)
rownames(gene_length_avg) <- gene_length_avg$ensembl_gene_id

# Obtain lengths in same order as counts
gene_length_ordered <- gene_length_avg[ensembl_ids, "transcript_length"]
names(gene_length_ordered) <- rownames(counts_filtered2)

# Filter genes without length
valid_idx <- !is.na(gene_length_ordered)
counts_filtered2 <- counts_filtered2[valid_idx, ]
gene_length_ordered <- gene_length_ordered[valid_idx]
ensembl_ids <- ensembl_ids[valid_idx]

# Convert to kilobases for TPM
gene_length_kb <- gene_length_ordered / 1000

# ---- Step 2. Calculate CPM and TPM ----
dge <- DGEList(counts = counts_filtered2)
dge <- calcNormFactors(dge)  # TMM normalization
cpm_values <- cpm(dge, log = FALSE)

calculateTPM <- function(counts, gene_length_kb) {
  rate <- counts / gene_length_kb
  tpm <- t(t(rate) / colSums(rate)) * 1e6
  return(tpm)
}
tpm_values <- calculateTPM(counts_filtered2, gene_length_kb)

# ---- Step 3. Log-transformation and filtering ----
log_cpm <- log2(cpm_values + 1)
log_tpm <- log2(tpm_values + 1)

log_cpm_filtered <- log_cpm[apply(log_cpm, 1, function(x) var(x, na.rm = TRUE) > 0), ]
log_tpm_filtered <- log_tpm[apply(log_tpm, 1, function(x) var(x, na.rm = TRUE) > 0), ]

log_tpm_filtered <- log_tpm_filtered[rowSums(is.na(log_tpm_filtered)) < ncol(log_tpm_filtered), ]

constant_cols_cpm <- apply(log_cpm_filtered, 2, function(x) sd(x, na.rm = TRUE) == 0)
log_cpm_filtered <- log_cpm_filtered[, !constant_cols_cpm]

constant_cols_tpm <- apply(log_tpm_filtered, 2, function(x) sd(x, na.rm = TRUE) == 0)
log_tpm_filtered <- log_tpm_filtered[, !constant_cols_tpm]

# ---- Step 4. PCA ----
if (!exists("group_filtered2")) {
  stop("Error: 'group_filtered2' is not defined. Ensure it is created before this block.")
}

group_cpm <- group_filtered2[!constant_cols_cpm]
group_tpm <- group_filtered2[!constant_cols_tpm]

pca_cpm <- prcomp(t(log_cpm_filtered), scale. = TRUE)
pca_tpm <- prcomp(t(log_tpm_filtered), scale. = TRUE)

# ---- Step 5. PCA Visualization ----
pca_df_cpm <- data.frame(PC1 = pca_cpm$x[,1], PC2 = pca_cpm$x[,2],
                         group = group_cpm,
                         sample_name = colnames(log_cpm_filtered))

pca_df_tpm <- data.frame(PC1 = pca_tpm$x[,1], PC2 = pca_tpm$x[,2],
                         group = group_tpm,
                         sample_name = colnames(log_tpm_filtered))

plot_cpm <- ggplot(pca_df_cpm, aes(x = PC1, y = PC2, color = group)) +
  geom_point(size = 4) +
  geom_text(aes(label = sample_name), vjust = -1, size = 3) +
  labs(title = "PCA - log2(CPM + 1)", x = "PC1", y = "PC2") +
  theme_minimal()
ggsave("analisis_3/PCA_log2_CPM.png", plot = plot_cpm, width = 8, height = 6, dpi = 300)

plot_tpm <- ggplot(pca_df_tpm, aes(x = PC1, y = PC2, color = group)) +
  geom_point(size = 4) +
  geom_text(aes(label = sample_name), vjust = -1, size = 3) +
  labs(title = "PCA - log2(TPM + 1)", x = "PC1", y = "PC2") +
  theme_minimal()
ggsave("analisis_3/PCA_log2_TPM.png", plot = plot_tpm, width = 8, height = 6, dpi = 300)

# ---- Step 6. Final verifications ----
cat("Final genes in CPM:", nrow(log_cpm_filtered), "\n")
cat("Final genes in TPM:", nrow(log_tpm_filtered), "\n")
cat("Removed samples in CPM:", sum(constant_cols_cpm), "\n")
cat("Removed samples in TPM:", sum(constant_cols_tpm), "\n")






# Analysis 4. Top 300 genes (Rejected with 100 and 200 because p-value was not significant)
### Top 300 RNA-seq genes (R vs NR) ###

# Take original Excel
rna_top300 <- read.xlsx("RNA.xlsx", colNames = TRUE)

# Filter and sort by |LFC|
rna_top300 <- rna_top300 %>%
  filter(!is.na(LFC_highvs_low)) %>%
  mutate(abs_LFC = abs(LFC_highvs_low)) %>%
  arrange(desc(abs_LFC))

# Select top 300 genes
top300_rna <- head(rna_top300$gene_Symbol, 300)

# Filter those in DESeq2 ranking
rna_genes_top300_filtered <- intersect(unique(top300_rna), names(res_ranking))

message("RNA genes top300 total: ", length(top300_rna),
        " | In DESeq2 ranking: ", length(rna_genes_top300_filtered))

# Optional: filter by sufficiently high statistic
rna_genes_top300_topsmall <- rna_genes_top300_filtered[
  abs(res_ranking[rna_genes_top300_filtered]) > 1
]
length(rna_genes_top300_topsmall)

# GSEA with fgsea
set.seed(1234)

fgsea_rna_top300 <- fgsea(
  pathways = list(RNA_top300 = rna_genes_top300_filtered),
  stats = res_ranking
)

fgsea_rna_top300_topsmall <- fgsea(
  pathways = list(RNA_top300_small = rna_genes_top300_topsmall),
  stats = res_ranking,
  minSize = 15,
  maxSize = 1000,
  nPermSimple = 10000
)

# Sorted results
fgsea_rna_top300[order(padj)]
fgsea_rna_top300_topsmall[order(padj)]

# Enrichment plots
png("analisis_4/plotEnrichment_rna_top300.png", width = 800, height = 600)
print(plotEnrichment(rna_genes_top300_filtered, res_ranking) +
        ggtitle("RNA-seq top 300"))
dev.off()

png("analisis_4/plotEnrichment_rna_top300_topsmall.png", width = 800, height = 600)
print(plotEnrichment(rna_genes_top300_topsmall, res_ranking) +
        ggtitle("small RNA-seq top 300"))
dev.off()

# Heatmap with top 300 genes
plot_heatmap_for_geneset(
  top300_rna, counts_filtered, res_df, group_filtered,
  "analisis_4/heatmap_rna_top300.png", "Heatmap: RNA (Top 300)"
)
save.image(file = "comprobar.RData")
